/// <reference types="node" />
import { defineConfig, devices } from "@playwright/test";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// import dotenv from 'dotenv';
// import path from 'path';
// dotenv.config({ path: path.resolve(__dirname, '.env') });

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  /* Directory where the tests are located. */
  testDir: "./tests",
  /* Run tests in files in parallel */
  fullyParallel: true,

  /* TIMEOUTS */

  // Test timeout (default is 30_000 ms)
  // timeout: 120_000,
  // Expect timeout (default is 5 seconds)
  // expect: {
  //   timeout: 10_000,
  // },
  // Global timeout: timeout for the whole test run; There's no default globalTimeout
  //  globalTimeout: 3_600_000,

  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. and Run tests in parallel locally
  (no. of workers is based on the number of CPU cores) */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: "html",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('')`. */
    // baseURL: 'http://localhost:3000',

    //Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer
    trace: "retain-on-failure",
    headless: false,
    screenshot: "off",
    // "data-testid" attribute can be used by default in the getByTestId() method
    testIdAttribute: "data-test-id", // this testIdAttribute is used in tests/testIdLocator.spec.ts
    // storageState: "storageState.json", // using the storage state generated by the src/saveLoginStorage.ts file to maintain the login session
    // bypassCSP: true, // bypassing the Content Security Policy (CSP) to allow the tests to run without being blocked by CSP restrictions
    // launchOptions: {
    //   slowMo: 100, // slowing down the execution of the tests by 100ms to make it easier to observe the test execution and debug if necessary
    // },
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://localhost:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
