import { test, Page, expect } from "@playwright/test";

// IMPORTANT: Run src/saveLoginStorage.ts file before running below test/s

test.use({
  storageState: "storageState.json", // using the storage state generated by the src/saveLoginStorage.ts file to maintain the login session
});

test("Direct OrangeHRM Dashboard Page", async ({ page }) => {
  test.setTimeout(120_000); // this time will set this test's timeout to 20_000ms overrifing the default and config file timeouts.

  await page.goto(
    "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index",
  ); // directly navigating to the dashboard page (without login) as we are using the storage state
  //  to maintain the login session

  await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible({
    timeout: 10_000,
  }); // this statement has inline Expect timeout explicitly set to 10_000 ms;
  // This overrides the default 5 sec or any specific Expect timeout mentioned in the config file
  // Here asserting that the dashboard heading is visible to confirm that we are on the dashboard page
  // and the login session is maintained
});
